name: Hello GitHub Actions

on:
  push:
    branches:
      - '**'

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Hello world action step
        run: echo "Hello World!"

      - name: Show current directory
        run: ls -al
